version : '3'
services:
    user-service:
        build: './user-service'
        depends_on:
            - user-service-db
        environment: 
            - DB_URI=mysql://root:password@user-service-db/db?charset=UTF8
        volumes: 
            - ./user-service:/app
        ports: 
            - 0.0.0.0:8080:8080

    user-service-db :
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=db
        restart: always
        image: mysql:5.7.20
        ports: 
            - 0.0.0.0:3307:3306

